### ISSUE TITLE
When testing Add Product, the new product did not appear and now No products show up

### ISSUE THREAD

**Issue by uskudarli** [sarahbe/-SWE573-SoftwarePractice#31]
I was testing adding a new product:

Name: Yesil Mercimek
Category: Baklagiller (a category I created)
Description: Something about protein, delicious, etc. 
![mercimek_yesil](https://cloud.githubusercontent.com/assets/1347035/15603878/f7865caa-2405-11e6-8ea8-6aeb701524e9.gif)

Producer: Mehmet
Origin: Izmir
Image (Attached)

The new product did not appear.

So, I tried to create it again.

Now nothing shows up. No products on Products Page.

**Comment by uskudarli** [comment]
The response for products page returned:

HTTP/1.1 404 Not Found
Server: Apache-Coyote/1.1
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-XSS-Protection: 1; mode=block
X-Frame-Options: DENY
x-content-type-options: nosniff
Content-Length: 0
Date: Fri, 27 May 2016 09:25:52 GMT

**Comment by sarahbe** [comment]
İn progress

**Comment by sarahbe** [comment]
Hello, 
First of all thanks for you patience. 
As mentioned in the report, some pages do not support validations yet. For example, when leaving some fields blank the data might be saved with wrong values. Especially drop down lists, when left to default value, (-1) is saved to database. And this is what causes the problem you faced today.  
For the blank fields I have fixed the issue by adding default values to columns. 
And for the drop down lists I will do my best to fix it as soon as possible and deploy the system again.

**Comment by uskudarli** [comment]
I was the products are back. So I tried again with Yesil Mercimek / Baklagil.

Again, the same thing happened.

Is it the image size? Type? 

It is very strange that 404 status code is returned. Do you know what is happening?

**Comment by sarahbe** [comment]
no it is not the size image. I have checked the database, it looks that you have tried to save a product called "Yesi" and the other fields were empty. this is why the error appeared again. 
Anyway the second product appears in the page. Could you please check it again ?

**Comment by sarahbe** [comment]
The bug is not closed yet. After deployment when the bug is fixed I will close the issue.

**Comment by sarahbe** [comment]
bug is fixed. 
As mentioned above, if one of the drop down list values were not selected the page would break down. 
now it is fixed. validation is added. :)
